### ISSUE TITLE
Clean up folders

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/website-old#16]
Delete folders no longer needed:

- Double check .idea folder can now be deleted
- There is a 'to be deleted' folder with some old css and js

**Comment by jhenshall** [comment]
@Hagellach37 - do you know if the .idea folder can be deleted? It hasn't been touched for 3 years. Sure it's not needed for the website but just want to double check it's not doing something I don't know about.

**Comment by Hagellach37** [comment]
yes you can delete it.
