### ISSUE TITLE
Build site using Actions on GitHub

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/website-old#24]
Move the `gulp build` to Actions on GitHub. Should simplify the workflow and make it easier for on-the-fly minor changes.

**Comment by jhenshall** [comment]
I've had a go at creating the action but have no idea if it will work and not even sure how to test it. Branch: https://github.com/mapswipe/website/tree/github-actions-build
@laurentS - any ideas on whether this will work and how to test?

**Comment by laurentS** [comment]
I think you'll need a step to actually deploy the site after what you've written. This [example](https://github.com/marketplace/actions/github-pages-action) might help.

As for testing, I don't know if they've made a good system for testing CI this time. The only solution I've seen before was to commit/push every change to a (temporary) branch and see what happens. For some systems, you might be able to install the CI toolchain locally, but I'm not sure it's worth it.
