### ISSUE TITLE
markdown style for descriptions aren't rendered on website page for project

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/website-old#58]
If a project description uses markdown to be nicely style in the app, it renders as a confusing string on the website.
Example: https://mapswipe.org/en/project.html?projectId=-Lwdhk8Ui3s2ah7IGBJi
<img width="745" alt="Screen Shot 2022-01-18 at 11 33 26 AM" src="https://user-images.githubusercontent.com/4806884/149978617-f4ecedf0-fe0b-40ab-a79c-427ad5137274.png">

**Comment by tnagorra** [comment]
We are adding support to render markdown text on the mapswipe website.




![Image](https://github.com/mapswipe/website/assets/4928045/04171fd7-4d17-40d8-863c-c23cb09b67fd)
