### ISSUE TITLE
Add link to the latest version apk

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/website-old#6]
As well as calls to download from the App Store and Google Play, we should link to the apk.

To be accurate, this will be dependant on mapswipe/mapswipe#149 being completed that will ensure the same link always points to the latest version apk.

The link is likely to be this but will need testing after above ticket completed: https://github.com/mapswipe/mapswipe/releases/latest

**Comment by danbjoseph** [comment]
link is https://github.com/mapswipe/mapswipe/releases/latest/download/app-production-release.apk 
and it was added to the website at some point after this issue was opened
