### ISSUE TITLE
dynamic stats on landing page

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/website-old#61]
> More than 30,000 volunteers engaged.
With over 1,000,000 sq km swiped.
Across 29 countries.

Can we replace the static numbers currently used with an API call for current number(s)?
Noting that the sq km total doesn't accurately include the new project types.

**Comment by laurentS** [comment]
See #17 for some ideas on how to implement this.
I think purely dynamic might be slow/expensive unless we can cache the results somewhere.

We actually have some of these stats (area mapped) on this page https://mapswipe.org/en/data.html which are crunched on each page load. The geojson file weighs over 1MB now, which is a lot just to produce one number. I'd lean towards setting up a github actions job that runs weekly or daily to update that number, either directly in the page(s) or in a small stats file that we can then fetch on each page load. And we can add the other 2 numbers in there at the same time.

I'm not sure what the best option would be to get the number of volunteers, as I'm not even sure how we defined this number in the first place: number of accounts on firebase? number of active users in the past X months?

As for the countries mapped, I think we could extract that from the same geojson file as the area, unless we have a better source.

**Comment by danbjoseph** [comment]
copied these comments over to the existing issue and closing this one as a duplicate.
